version: 2
updates:
  # Configuration for Go modules
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "monthly"

  # Configuration for npm (React)
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "monthly"
