query GetUser($id: String!) {
  user(id: $id) {
    id 
    userId
    email
    name
    picture
    givenName
    familyName
    hd
    settings {
      theme
      locale
    }
    lastLogin
    createdAt
    updatedAt
  }
}