/* tslint:disable */
/* eslint-disable */
/**
 * Keep Clone
 * Rest endpoints
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NoteRequest
 */
export interface NoteRequest {
    /**
     * Title of the note
     * @type {string}
     * @memberof NoteRequest
     */
    title?: string;
    /**
     * Body content of the note
     * @type {string}
     * @memberof NoteRequest
     */
    body?: string;
    /**
     * Status of the note
     * @type {string}
     * @memberof NoteRequest
     */
    status?: NoteRequestStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum NoteRequestStatusEnum {
    ARCHIVED = 'ARCHIVED',
    DELETED = 'DELETED',
    ACTIVE = 'ACTIVE'
}

