name: Deploy Server AWS

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build-test-server:
    name: Build/Test Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache-dependency-path: 'server/go.sum'

    - name: Test
      working-directory: server
      run: go test ./...

    - name: Build
      working-directory: server
      run: go build -v .

  build-and-push-server:
    name: Build/Push Server
    needs: 
      - build-test-server
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push server image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        SERVER_ECR_REPOSITORY: keep_server
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$SERVER_ECR_REPOSITORY:$IMAGE_TAG ./server
        docker tag $ECR_REGISTRY/$SERVER_ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$SERVER_ECR_REPOSITORY:$GITHUB_SHA
        docker push $ECR_REGISTRY/$SERVER_ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$SERVER_ECR_REPOSITORY:$GITHUB_SHA