name: Server

on:
  push:
    paths:
      - 'server/**'
      - 'go.work'
      - 'go.work.sum'
      - '.github/workflows/server.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache-dependency-path: 'server/go.sum'

    - name: Test
      working-directory: server
      run: go test ./...

    - name: Build
      working-directory: server
      run: go build -v .