name: Validate OpenAPI Specification

on:
  push:
    paths:
      - 'keep-clone.yaml'
      - '.github/workflows/spec.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Validate OpenAPI Specification using Speccy
      run: npx @apidevtools/swagger-cli validate keep-clone.yaml