name: UI

on:
  push:
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: yarn install
      working-directory: ui

    - name: Build
      run: yarn build
      working-directory: ui