name: UI

on:
  pull_request:
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ui/node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('ui/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-${{ hashFiles('ui/yarn.lock') }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.6.1'
        cache-dependency-path: './ui/yarn.lock'

    - name: Install Dependencies
      run: yarn install
      working-directory: ui

    - name: Lint
      run: yarn lint
      working-directory: ui

    - name: Build
      run: yarn build
      working-directory: ui