name: UI

on:
  push:
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.x'
        cache-dependency-path: './ui/yarn.lock'
        cache: yarn

    - name: Install Dependencies
      run: yarn install
      working-directory: ui

    - name: Lint
      run: yarn lint
      working-directory: ui

    - name: Build
      run: yarn build
      working-directory: ui